name: Check Conformance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint
    - name: Lint with flake8
      run: |
        flake8 ./gdlevelconverter --count --show-source --statistics --max-line-length=100
    - name: Lint with pylint
      run: |
        pylint ./gdlevelconverter
    - name: Test with unittest
      run: |
        python -m unittest discover
